AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  discord-slash-commands

  Slash command application for discord server.

Globals:
  Function:
    Timeout: 3

Resources:
  DiscordSlashCommandFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        DiscordSlashCommand:
          Type: Api
          Properties:
            Path: /discord_slach_command
            Method: post
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./discord-slash-commands
      Dockerfile: Dockerfile

Outputs:
  DiscordSlashCommandApi:
    Description: "API Gateway endpoint URL for Prod stage for discord slash command function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/discord_slach_command/"
  DiscordSlashCommandFunction:
    Description: "discord slash command Lambda Function ARN"
    Value: !GetAtt DiscordSlashCommandFunction.Arn
  DiscordSlashCommandFunctionIamRole:
    Description: "Implicit IAM Role created for discord slash command function"
    Value: !GetAtt DiscordSlashCommandFunctionRole.Arn
